version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=school
      - POSTGRES_PASSWORD=schoolpass
      - POSTGRES_DB=schooldb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=devsecret
      - DATABASE_URL=postgresql://school:schoolpass@postgres:5432/schooldb
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
